definitions:
  api.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  api.createBookingReq:
    properties:
      end_date:
        type: string
      lat:
        type: number
      long:
        type: number
      prefered_nurse:
        type: integer
      start_date:
        type: string
      type:
        type: string
    required:
    - end_date
    - lat
    - long
    - start_date
    - type
    type: object
  db.Request:
    properties:
      created_at:
        type: string
      end_date:
        type: string
      id:
        type: integer
      location: {}
      prefered_nurse:
        type: integer
      start_date:
        type: string
      type:
        type: string
      user_id:
        type: integer
    type: object
info:
  contact: {}
paths:
  /bookings/request:
    post:
      consumes:
      - application/json
      description: get accounts
      parameters:
      - description: create booking request by user
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/api.createBookingReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/db.Request'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      security:
      - bearerAuth: []
      summary: List accounts
      tags:
      - accounts
securityDefinitions:
  bearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
